### ISSUE TITLE
Adjust URLs

### ISSUE THREAD

**Issue by zkdev** [keycloud/docs#1]
Since we're using a reverse proxy the YouTrack and TeamCity URLs changed. Thus we have to adjust the URLs inside our blogposts.

**YouTrack**: `https://youtrack.zeekay.dev`
**TeamCity**: `https://teamcity.zeekay.dev`

**Comment by zkdev** [comment]
- top right corner (@zkdev)
- Midterm: Project Management (@hottek)
- Midterm: Quality (@hottek)
- Week 06: Scrum (@hottek)

**Comment by hottek** [comment]
done
